
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication
  ports:
    - port: 80
      targetPort: 80
  clusterIP: None  # This allows other services to communicate directly with it