apiVersion: v1
kind: Service
metadata:
  name: storage-management-service
spec:
  selector:
    app: storage-management
  ports:
    - port: 80
      targetPort: 80
  clusterIP: None  # This allows other services to communicate directly with it
