apiVersion: v1
kind: Service
metadata:
  name: video-streaming-service
spec:
  selector:
    app: video-streaming
  ports:
    - port: 80
      targetPort: 80
  clusterIP: None  # To allow other services to directly access the service