apiVersion: v1
kind: Service
metadata:
  name: video-delete-service
spec:
  selector:
    app: video-delete
  ports:
    - port: 80
      targetPort: 80
  clusterIP: None  # This allows other services to communicate directly with it
